### ISSUE TITLE
When will more code be released?

### ISSUE THREAD

**Issue by pkulium** [SchwinnL/LLM_Embedding_Attack#1]
Great work! When will more code be released for the paper(Soft Prompt Threats: Attacking Safety Alignment and Unlearning in
Open-Source LLMs through the Embedding Space)?

**Comment by SchwinnL** [comment]
Hi, 

I appreciate your interest!
I'm planning to release the code in the following two weeks.

**Comment by SchwinnL** [comment]
Hi, unfortunately, I got sick and have not been able to upload the code yet.
If you want you can send me an email: l.schwinn@tum.de, and I will send you the original non-refactored code.
